# Uncomment the next line to define a global platform for your project
platform :ios, '10.2'

target 'FirebaseSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseSwift
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
end
